api/urls.py
from django.urls import path, include
from .views import todoView, todojson
app_name = "api"
urlpatterns = [
    path('activities/', todoView.as_view(), name="todo"),
    path('todojson/', todojson, name="todojson"),
    path('activities/<int:id>', todoView.as_view(), name="delete_todo"),
]

luo_blog/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('my_blog.urls',namespace='my_blog')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('api/', include('api.urls', namespace='api')),
]

my_blog/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'my_blog'

urlpatterns = [
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path('category/', views.category, name='category'),
    path('category/<int:category_id>/',views.category_articles, name='category_articles'),
]

my_blog/models.py
from django.db import models

# Create your models here.
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from django.urls import reverse

#
class ArticleColumn(models.Model):
    """
    栏目的模型
    """
    # 栏目的标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 统计文章访问量
    total_view = models.PositiveIntegerField(default=0)
    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 文章栏目的“一对多”外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

    def get_absolute_url(self):
        return reverse('my_blog:article_detail', args=[self.id])

my_blog/forms.py
from django import forms

from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

my_blog/views.py
from django.shortcuts import render, redirect
# Create your views here.
from .models import ArticlePost
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入栏目Model
from .models import ArticleColumn
# 引入HttpResponse
from django.http import HttpResponse
# 引入User模型
from django.contrib.auth.models import User
# 引入分页模块
from django.core.paginator import Paginator
# 引入 Q 对象
from django.db.models import Q
# Comment 模型
from comment.models import Comment
from comment.forms import CommentForm
# 引入装饰器
from django.contrib.auth.decorators import login_required
import markdown


def article_list(request):
    # 查询文章数量
    num = len(ArticlePost.objects.all())
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'total_view':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_view')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        search = ''
        if order == 'total_view':
            article_list = ArticlePost.objects.all().order_by('-total_view')
        else:
            article_list = ArticlePost.objects.all()
    # 每页显示一篇文章
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {'articles': articles, 'order': order, 'search': search, 'num': num}

    return render(request, 'my_blog/list.html', context)


def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    # 浏览次数
    # 只更新total_view字段
    article.total_view += 1
    article.save(update_fields=['total_view'])
    comments = Comment.objects.filter(article=id)
    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展
            'markdown.extensions.toc',
        ])
    # 需要传递给模板的对象
    article.body = md.convert(article.body)
    comment_form = CommentForm()
    context = {
        'article': article,
        'toc': md.toc,
        'comments': comments,
        'comment_form': comment_form
    }

    return render(request, 'my_blog/detail.html', context)


def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            print(request.user.id)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            return redirect("my_blog:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'my_blog/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)

        article.delete()

        return redirect("my_blog:article_list")
    else:
        return HttpResponse("仅允许post")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                # 这一行代码需要详细解释
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            return redirect("my_blog:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article': article, 'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'my_blog/update.html', context)


def category(request):
    categories = ArticleColumn.objects.all()
    return render(request, 'my_blog/category.html', {'categories': categories})


def category_articles(request, category_id):
    print(category_id)
    category_name = ArticleColumn.objects.get(id=category_id)
    print(category_name)
    articles = ArticlePost.objects.filter(column=category_name)

    return  render(request, 'my_blog/category_articles.html', {'articles': articles})

templates/my_blog/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-8">
                <ul class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'my_blog:category_articles' category.id %}" class="list-group-item">{{ category.title }}<span>{{ category.id }}</span></a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>




{% endblock %}

templates/my_blog/category_articles.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for article in articles %}
        <!-- 文章内容 -->
                <div class="col-12 article-card" style=" border: 1px solid #00000020; margin-top: 15px ; border-radius: 4px">
                <!-- 栏目 -->
            {% if article.column %}
                <button type="button"
                    class="btn btn-sm mb-2
                        {% if article.column.title == 'django' %}
                            btn-success
                        {% elif article.column.title == 'mysql' %}
                            btn-danger
                        {% elif article.column.title == 'html5' %}
                            btn-success
                        {% elif article.column.title ==
                        'python' %}
                            btn-warning
                        }
                        {% elif article.column.title ==
                        'others' %}
                            btn-danger
                        {% endif %}
                    "
                >
                    {{ article.column }}
                </button>
            {% endif %}
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'my_blog:article_detail' article.id %}"
                       style="color: black;"
                    >
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span style="color: lightskyblue;">
                    {{ article.total_view}} 浏览&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: yellowgreen;">
                    {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: pink;">
                    {{ article.updated|date:'Y-m-d' }} 更新
                </span>
            </p>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/my_blog/create.html
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control" 
                        id="column" 
                        name="column"
                    >
                    <option value="none">请选择栏目..</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                    {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/my_blog/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-12">
        <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
            作者：{{ article.author }}  
            {% if user == article.author %}

                <a href="#" onclick="confirm_safe_delete()">删除文章</a> 
                <a href="{% url "my_blog:article_update" article.id %}">修改文章</a>
            {% endif %}
        </div>
        <div>
            浏览：{{article.total_view}}
        </div>
       <div class="col-12">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>

<form
      style="display:none;" 
      id="safe_delete"
      action="{% url 'my_blog:article_safe_delete' article.id %}" 
      method="POST"
>
{% csrf_token %}
<button type="submit">发送</button>
</form>
    <!-- 文章正文 -->
        <div class="col-10">
        <p  style="text-align: center;">{{ article.body|safe}}</p>
        </div>


    {% include 'comment/comment_list.html' %}
<script>
function confirm_safe_delete() {
    layer.open({
        title: "确认删除",
        content: "确认删除这篇文章吗？",
        yes: function(index, layero) {
            $('form#safe_delete button').click();
            layer.close(index);
        }
    })
}
</script>
{% endblock content %}

templates/my_blog/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'my_blog:article_list' %}?search={{search}}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'my_blog:article_list' %}?order=total_view&search={{search}}">
                    最热
                </a>
            </li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-6">
            <p>您已创作{{num}}篇文章。</p>
        </div>
    </div>
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text" 
                    class="form-control mb-2 mr-sm-2" 
                    name="search" 
                    placeholder="搜索文章..." 
                    required
                >
            </form>
        </div>
    </div>
    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>        
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-12 article-card" style=" border: 1px solid #00000020; margin-top: 15px ; border-radius: 4px">
            <!-- 栏目 -->
            {% if article.column %}
                <button type="button" 
                    class="btn btn-sm mb-2
                        {% if article.column.title == 'django' %}
                            btn-success
                        {% elif article.column.title == 'mysql' %}
                            btn-danger
                        {% elif article.column.title == 'html5' %}
                            btn-success
                        {% elif article.column.title ==
                        'python' %}
                            btn-warning
                        }
                        {% elif article.column.title ==
                        'others' %}
                            btn-danger
                        {% endif %}
                    "
                >
                    {{ article.column }}
                </button>
            {% endif %}
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'my_blog:article_detail' article.id %}"
                       style="color: black;" 
                    >
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span style="color: lightskyblue;">
                    {{ article.total_view}} 浏览&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: yellowgreen;">
                    {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: pink;">
                    {{ article.updated|date:'Y-m-d' }} 更新
                </span>
            </p>
        </div>
    {% endfor %}        

    </div>
</div>
    <!-- 页码导航 -->
<div class="pagination row" style="margin-top: 60px">
    <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&order={{order}}&search={{search}}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{order}}&search={{search}}" 
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{order}}&search={{search}}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{order}}&search={{search}}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

templates/my_blog/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div for="form-group">
                    <label for="column">文章栏目</label>
                    <select class="form-control" 
                    id="column" 
                    name="column"
                    >
                    <option value="none">请选择栏目..</option>
                {% for column in columns %}
                    <option value="{{ column.id }}"
                    {% if column.id == article.column.id %}
                        selected
                    {% endif %}
                >
                    {{ column }}
                    </option>
                {% endfor %}
                    </select>   
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>

        </div>
    </div>
</div>
{% endblock content %}