api/urls.py
from django.urls import path, include
from .views import todoView, todojson
app_name = "api"
urlpatterns = [
    path('activities/', todoView.as_view(), name="todo"),
    path('todojson/', todojson, name="todojson"),
    path('activities/<int:id>', todoView.as_view(), name="delete_todo"),
]

luo_blog/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('my_blog.urls',namespace='my_blog')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('api/', include('api.urls', namespace='api')),
]

my_blog/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'my_blog'

urlpatterns = [
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path('category/', views.category, name='category'),
    path('category/<int:category_id>/',views.category_articles, name='category_articles'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete<int:id>/',views.user_delete,name='delete'),
    path('changepwd/', views.change_password, name="changepwd"),
]

templates/api_todo.html
<!DOCTYPE html>
<html lang="en">
<title>to do list</title>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Vue Todo</title>
    <style>
        .completed {
            text-decoration: line-through;
        }

        .selected {
            color: red;
        }
    </style>
</head>
<body>
<div id="todo-app">
    <div>
        <input type="button" value="获取数据" @click="get_data"/>
        <input type="button" value="保存数据" @click="store_data"/>
        <input type="button" value="全部标为完成" @click="markAsallcompleted"/>
        <input type="text" v-model="newTodoTitle" @keyup.enter="addTodo" placeholder="添加 todo"/>
    </div>
    <!-- todo list -->
        <ul>
            <li v-for="todo in todos"  :key="todo.id">
                <!-- 绑定类 -->
                <span :class="{completed:todo.completed}" @dblclick="editItem(todo)">{% verbatim myblock %}{{ todo.title}}{% endverbatim myblock %}</span>
                <input v-if="!todo.completed"  value="标为完成" type="button" @click="markAsCompleted(todo)">
                <input type="button" value="删除" @click="removeItem(todo)">
                <input type="text" value="编辑 todo..." v-if="editedTodo!==null && editedTodo.id===todo.id" v-model="todo.title"
                @keyup.enter="editDone(todo)"/>
                <input v-if="todo.completed" type="button" value="撤销操作" @click="markAsundone(todo)">
            </li>
        </ul>
    <!-- end todo list -->
    <div>
        <span>剩余 3 项未完成 ---</span>
        <span>筛选：
      <input type="button" class="selected" value="全部">
      <input type="button" value="进行中">
      <input type="button" value="已完成">
      <input type="button" value="清除已完成">
      <input type="button" value="清除全部">
    </span>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>

    const app = new Vue({
        el:'#todo-app',
        data: {
                newTodoTitle: '',
                todos: [
                {id: 0, title: '学习 Vue', 'completed':false},
                {id: 1, title: '整个牛项目', 'competed':false},
                {id: 2, title: '迎娶白富美走上人生巅峰', 'completed':false},

                ],
                editedTodo:null
        },
        methods: {
            get_data: function() {
                var that = this;
                axios.get('/api/todojson')
                .then(function (response) {
                    this.todos = {'title': 'hahhaha'};
                    obj_list = response.data;
                    new_obj_list = [];
                    for (let i=0; i<obj_list.length; i++){
                        let new_obj = {'id':null, 'title':null, 'completed':null};
                        new_obj['id'] = obj_list[i]['pk'];
                        new_obj['title'] = obj_list[i]['fields']['title'];
                        new_obj['completed'] = obj_list[i]['fields']['completed']
                        new_obj_list.push(new_obj);
                    }
                    that.todos = new_obj_list;
                })
                .catch(function (error) {
                    console.log(error);
                });
            },
            store_data: function(){
                let jsondata = '';
                for (let i=0;i<this.todos.length;i++)
                {
                    let temp = JSON.stringify(this.todos[i]);
                    jsondata +=temp;
                    jsondata+' ';
                }
                console.log(jsondata);
                axios
                .post('/api/activities/',jsondata)
                .then(function (response) {
                    console.log(response);
                })
                .catch(function (error) {
                    console.log(error);
                })
            },
            addTodo: function () {
                 let id = this.todos.length;
                 ++id;
                this.todos.push({id: ++id, title: this.newTodoTitle, completed:false});
                this.newTodoTitle = ''
                console.log(this.todos);
            },
            markAsCompleted: function (todo) {
                todo.completed = true;
            },
            markAsundone: function (todo) {
                todo.completed = false;
            },
            removeItem: function (todo) {
                alert("确定要删除？");
                this.todos.splice(this.todos.indexOf(todo), 1);
                axios.delete(''+todo.id)
                .then(function (response) {
                    console.log(response);
                }).catch(function (error) {
                    console.log(error);
                })
            },
            editItem: function (todo) {
                this.editedTodo = {id: todo.id, title: todo.title}
            },
            editDone: function (todo) {
                this.editedTodo = null;
            },
            markAsallcompleted: function () {
                console.log('run');
                for (let i=0;i<this.todos.length;i++){
                    if (!(this.todos[i].completed)){
                        this.todos[i].completed = true;
                    }
                }
            }
        }
    })
</script>
</body>
</html>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"  href="{% static 'md_css/manni.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>    
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        #nav-footer{
            height: 100px;
            margin-top:300px;
        }
    </style>
</body>
</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->

<footer class="py-3 bg-dark" id="footer">
	<div class="container">
	    <p class="m-0 text-center text-white">Copyright &copy; www.luoziqiang.com 2020</p>
	</div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-md navbar-fixed-top navbar-light">
    <div class="container">

	<!-- 导航栏商标 -->
	<a class="navbar-brand" href="http://www.luoziqiang.com">Codeplay</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
	<!-- 导航入口 -->
	<div class="collapse navbar-collapse" id="navbarCollapse">
	    <ul class="nav navbar-nav ml-auto">
		<!-- 条目 -->
		<li class="nav-item">
		    <a class="nav-link" href="{% url 'my_blog:article_list' %}">文章</a>
		</li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'my_blog:category' %}">文章分类</a>
        </li>
		<li class="nav-item" style="margin-left: 10px">
		    <a class="nav-link" href="{% url 'my_blog:article_create' %}">写文章</a>
		</li>
		{% if user.is_authenticated %}
		<!-- 如果用户已经登录，则显示用户名下拉框 -->
		<li class="nav-item dropdown " style="margin-left:10px">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  {{ user.username }}
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
				<a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
			    <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                <a class="dropdown-item" href="{% url 'userprofile:changepwd' %}">更改密码</a>
			</ul>
		</li>
	<!-- 如果用户未登录，则显示 “登录” -->
	   {% else %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
		</li>                    
	<!-- if 语句在这里结束 -->
	   {% endif %}
	  </ul>
	</div>

  </div>
</nav>
{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

templates/test_axios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学习使用axios</title>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<body>
    <div id="app">
        {{ info }}
    </div>
</body>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script>
        const app = new Vue({
            el:'#app',
            data() {
                return{
                    info: null
                }
            },
            mounted () {
                axios.get('https://www.runoob.com/try/ajax/json_demo.json')
                .then(function (response) {
                    this.info = response;
                })
                .catch(function (error) {
                    console.log(error);
                });
            }
        })
    </script>
</html>